### ISSUE TITLE
Projects with no dependencies overwrite the file with "undefined"

### ISSUE THREAD

**Issue by mcnallys** [jeffpriz/vsts-nuspec-reference-update#4]
When a project has no dependencies the entire nuspec is overwritten with "undefined"

Should success variable in dowork be set as false for the default value?

https://github.com/jeffpriz/vsts-nuspec-reference-update/blob/master/NuspecUpdate/src/taskRun.ts

updatedNusepec is not defined unless there are references, but the file is still written because success is true.

**Comment by jeffpriz** [comment]
@mcnallys thanks for reporting the issue.. I am having some trouble reproducing it. I've created a branch "project-with-no-refs" https://github.com/jeffpriz/vsts-nuspec-reference-update/tree/project-with-no-refs
to try to test this. I've added a test with a project that has no nuget dependencies in it, and the step seems to run as expected.. the dependencies list comes back as a zero length array, and the logic currently checks the length of the array to see if it should do anything.. and in the end the nuspec file remains unchanged.. 

Can you perhaps update the project file to cause the issue that you're seeing?
https://github.com/jeffpriz/vsts-nuspec-reference-update/blob/project-with-no-refs/NuspecUpdate/src/test/NugetSampleTestNoRef.csproj

**Comment by ghostshadow79** [comment]
@jeffpriz I'm facing the same problem. It started to happen when I changed the project to use packages.config instead of the csproj references.

Hope it helps

**Comment by jeffpriz** [comment]
@ghostshadow79 This task is not designed to use packages.config.. this task is designed to work with projects that have moved away from that and to the newer format of keeping the references in the project.
https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference


there are other marketplace tasks that should help you with this same thing for projects that still use packages.config

**Comment by jeffpriz** [comment]
key thing that I take away from Microsoft's statement about packages.config:

**PackageReference is under active development: See PackageReference issues on GitHub. packages.config is no longer under active development.**

**Comment by ghostshadow79** [comment]
Thanks for the reply. Made the change and worked.

Cheers

**Comment by mcnallys** [comment]
We've moved away from using this task, nothing against the task just went a different route for producing our packages. 

Maybe have an error come up when packages.config is used?
